//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAF()
        {
            this.TRACKING_CAF = new HashSet<TRACKING_CAF>();
        }
    
        public int ID_CAF { get; set; }
        public Nullable<int> ID_EMPESA { get; set; }
        public Nullable<int> FOLLIO_DESDE { get; set; }
        public Nullable<int> FOLIO_HASTA { get; set; }
        public string FECHA_CARGA { get; set; }
        public string ESTADO { get; set; }
        public string CAF1 { get; set; }
        public Nullable<int> TIPO_DOC_CAF { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACKING_CAF> TRACKING_CAF { get; set; }
    }
}
