//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADO_DIGITAL
    {
        public int ID_CERT { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public string RUTA_CERT { get; set; }
        public string PASS_CERT { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
