//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRIBUYENTE_SII
    {
        public int ID_CONTRIBUYENTE_SII { get; set; }
        public string RUT_CONTRIBUYENTE { get; set; }
        public string RZN_CONTRIBUYENTE { get; set; }
        public string FECHA_RESOLUCION { get; set; }
        public string EMAIL_CONTRIBUYENTE { get; set; }
        public string PAGINA_WEB_CONTRIBUYENTE { get; set; }
    }
}
