//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_LIBRO_COMPRA
    {
        public int ID_DETALLE_COMPRA { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<int> NRO_DOC { get; set; }
        public Nullable<int> ID_LIBRO_COMPRA { get; set; }
    
        public virtual LIBRO_COMPRA LIBRO_COMPRA { get; set; }
        public virtual DTE_RECEPCION DTE_RECEPCION { get; set; }
    }
}
