//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PROD
    {
        public int ID_DETALLE { get; set; }
        public int ID_EMPRESA { get; set; }
        public string NOMBRE { get; set; }
        public string CODIGO { get; set; }
        public string UMEDIDA { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public string DESCRIPCION_PRODUCTO { get; set; }
        public Nullable<decimal> VALOR_UNITARIO { get; set; }
        public string FECHA_CREACION { get; set; }
        public Nullable<int> DESCUENTO_PCT { get; set; }
        public string ESTADO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
