//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_LIBRO_VENTA
    {
        public int ID_DETALLE_VENTA { get; set; }
        public Nullable<int> ID_DTE { get; set; }
        public Nullable<int> ID_LIBRO_VENTA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual LIBRO_VENTA LIBRO_VENTA { get; set; }
        public virtual DTE_EMISION DTE_EMISION { get; set; }
    }
}
