//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTE_EMISION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DTE_EMISION()
        {
            this.DETALLE_LIBRO_VENTA = new HashSet<DETALLE_LIBRO_VENTA>();
            this.SEGUIMIENTO_DTE = new HashSet<SEGUIMIENTO_DTE>();
            this.TRACKING_CAF = new HashSet<TRACKING_CAF>();
        }
    
        public int ID_DTE { get; set; }
        public Nullable<int> ID_EMPESA { get; set; }
        public Nullable<int> TIPO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string FECHA_EMISION { get; set; }
        public Nullable<int> NUM_FOLIO { get; set; }
        public string ESTADO_RECEP { get; set; }
        public Nullable<decimal> MONTO_EXE { get; set; }
        public Nullable<decimal> MONTO_NETO { get; set; }
        public Nullable<decimal> MONTO_IVA { get; set; }
        public Nullable<decimal> MONTO_TOTAL { get; set; }
        public string RUTA_XML_ENV_SII { get; set; }
        public string RUTA_XML_ENV_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_LIBRO_VENTA> DETALLE_LIBRO_VENTA { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGUIMIENTO_DTE> SEGUIMIENTO_DTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACKING_CAF> TRACKING_CAF { get; set; }
    }
}
