//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_USU
    {
        public int ID { get; set; }
        public int ID_USU { get; set; }
        public int ID_EMP { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
