//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRO_COMPRA()
        {
            this.DETALLE_LIBRO_COMPRA = new HashSet<DETALLE_LIBRO_COMPRA>();
        }
    
        public int ID_LIBRO_COMPRA { get; set; }
        public Nullable<int> ID_EMPESA { get; set; }
        public string PERIODO_LIBRO { get; set; }
        public string FECHA_CREACION { get; set; }
        public string ESTADO_LIBRO { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_LIBRO_COMPRA> DETALLE_LIBRO_COMPRA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
