//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tyscom_FacturaEntities2 : DbContext
    {
        public Tyscom_FacturaEntities2()
            : base("name=Tyscom_FacturaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAF> CAF { get; set; }
        public virtual DbSet<CERTIFICADO_DIGITAL> CERTIFICADO_DIGITAL { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CONTRIBUYENTE_SII> CONTRIBUYENTE_SII { get; set; }
        public virtual DbSet<DETALLE_LIBRO_COMPRA> DETALLE_LIBRO_COMPRA { get; set; }
        public virtual DbSet<DETALLE_LIBRO_VENTA> DETALLE_LIBRO_VENTA { get; set; }
        public virtual DbSet<DETALLE_PROD> DETALLE_PROD { get; set; }
        public virtual DbSet<DTE_EMISION> DTE_EMISION { get; set; }
        public virtual DbSet<DTE_RECEPCION> DTE_RECEPCION { get; set; }
        public virtual DbSet<EMP_USU> EMP_USU { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ESTADO_SII> ESTADO_SII { get; set; }
        public virtual DbSet<LIBRO_COMPRA> LIBRO_COMPRA { get; set; }
        public virtual DbSet<LIBRO_VENTA> LIBRO_VENTA { get; set; }
        public virtual DbSet<PARAMETROS> PARAMETROS { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RUTA_GUARDADO_EMPRESA> RUTA_GUARDADO_EMPRESA { get; set; }
        public virtual DbSet<SEGUIMIENTO_DTE> SEGUIMIENTO_DTE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<TRACKING_CAF> TRACKING_CAF { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
