//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTA_GUARDADO_EMPRESA
    {
        public int ID_RUTA_GUARDADO { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public string RUTA_EMPRESA { get; set; }
        public string RUTA_ENVIO_SII { get; set; }
        public string RUTA_ENVIO_CLIENTE { get; set; }
        public string RUTA_CERT_DIGITAL { get; set; }
        public string RUTA_FOLIO { get; set; }
        public string RUTA_DTE_SII { get; set; }
        public string RUTA_DTE_CLIE { get; set; }
        public string RUTA_PDF { get; set; }
        public string RUTA_PDF_417 { get; set; }
        public string RUTA_XSLT { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
