//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_factura.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGUIMIENTO_DTE
    {
        public int ID_SEGUIMIENTO_DTE { get; set; }
        public int ID_DTE { get; set; }
        public int ID_ESTADO { get; set; }
        public string FECHA_ESTADO { get; set; }
        public string OBSERVACION_ESTADO { get; set; }
        public string FECHA_CREACION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual DTE_EMISION DTE_EMISION { get; set; }
        public virtual ESTADO_SII ESTADO_SII { get; set; }
    }
}
